Gemfile, Gemfile.lock, app/models/user.rb, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb, app/views/layouts/application.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20230228154104_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
I created the devise for the user model, and changed some view files to make the pop ups and messages work @Ayatamin25
=> User devise model made, pls check

app/models/doll.rb, db/migrate/20230227223103_create_dolls.rb, db/migrate/20230228161645_add_user_foreign_key_to_dolls.rb, db/schema.rb, test/models/doll_test.rb
- Doll model created
- check schema
@Ayatamin25 please verify and merge when all good.
=> doll model created without user:references

config/routes.rb
- changed root to get '/'
@adhamkou please check and merge when good
=> changed root to get / in routes.rb

app/controllers/application_controller.rb, app/controllers/pages_controller.rb, app/views/devise/registrations/new.html.erb, app/views/layouts/application.html.erb, app/views/shared/_flashes.html.erb, db/migrate/20230228170845_add_name_to_users.rb, db/schema.rb
pls check the controller and views, for sign up and authentication @Ayatamin25
=> did the views and controller for the devise users

Gemfile.lock, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_cardcategory.scss, app/assets/stylesheets/components/_cardproduct.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_searchform.scss, app/assets/stylesheets/components/_tabs.scss
=> added the scss components 

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
=> updated the navbar componenets

.gitignore, Gemfile, Gemfile.lock, app/controllers/dolls_controller.rb, app/models/doll.rb, app/views/dolls/index.html.erb, app/views/dolls/new.html.erb, app/views/dolls/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/routes.rb, config/storage.yml, db/migrate/20230228185402_create_active_storage_tables.active_storage.rb, db/schema.rb
- adjusted the routes for new, create & show
- created new, create, show action in Doll controller
- Added the form in new.html.erb
- Created a show.html.erb
- Linked cloudinary to db
- added has_one_attached :image to Doll model
- created the .env
- adjusted the index and show views to see name, description, price, location and image 
- Added validates :name, :description, :price, :location, :image in Doll model
- Added private method doll_params in controller
@Ayatamin25 could you check please and merge when verified
=> Add new/create to doll

app/views/shared/_navbar.html.erb, config/routes.rb
- added link_to all the buttons and logo on the navbar(no booking link yet)
- added as: :home in the home route
@Ayatamin25 please check and merge when all good
=> added links to nav bar

.env, app/assets/stylesheets/components/_cardsgrid.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> added cards to home page

app/views/pages/home.html.erb
=> Edit home page and styleit

app/assets/stylesheets/components/_cardproduct.scss, app/views/dolls/index.html.erb, app/views/dolls/show.html.erb
- added card html and scss to doll show and index
- got rid of text-decoration for links
- made cards clickable
- changed text-color to dark
@Ayatamin25 please check and merge when good
=> Create cards in show and index

app/controllers/bookings_controller.rb, app/views/bookings/my_bookings.html.erb, app/views/bookings/new.html.erb, db/schema.rb
=> all the bookings path working well

db/migrate/20230301135401_add_default_value_to_bookings.rb, db/schema.rb
@Ayatamin25 , i just add the default value to the column of status on bookings table, please check if correct
=> Add default status

app/views/dolls/show.html.erb, app/views/shared/_navbar.html.erb, db/schema.rb, node_modules/.yarn-integrity
- added a btn in cards in doll show page that links to a bookings/new (form)
- stylized btn a little bit with bootstrap
- Added a link_to my_bookings in nav
@Ayatamin25 please check and merge when good
=> Add link to booking request on cards

app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb
@CloneProtocolSixtySix  i delete doll selection from booking table
=> remove the doll selection from booking table

app/assets/stylesheets/components/_footer.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb
@maggiehum 
- footer render is found in 
veiws/layouts
-html footer code found within 
views/shared
no scss was changes except for black to white
=> fixed footer

app/controllers/dolls_controller.rb, app/views/shared/_navbar.html.erb
- Added the link to dolls index in nav bar for it to be seen in home page without begin signed in
- added skip_before_action :authenticate_user!, only: :index in dolls controller
@Ayatamin25 please check and merge when good
=> skip before action authentication for index

app/controllers/bookings_controller.rb, app/views/bookings/my_bookings.html.erb, app/views/bookings/set_status.html.erb, app/views/bookings/status.html.erb, config/routes.rb
@maggiehum 
set_status page: add radio button for user change the status to confirm if accept the booking or not
my_bookings page: add link to each booking, jump to booking confrimation , which is meant set_status page
=> finish the status button

app/views/dolls/show.html.erb
=> changed the word when asking to delete

app/controllers/dolls_controller.rb, app/models/doll.rb
fixed the controller @maggiehum
=> Fixed destroy

db/seeds.rb
- fixed the seeds(changed the pictures)
- added destroy Booking.destroy_all at top of page
@Ayatamin25
=> Heroku bugfix

app/controllers/application_controller.rb, app/controllers/dolls_controller.rb, app/views/layouts/application.html.erb
fixed first and last name @youpancan
=> First name userr

app/controllers/dolls_controller.rb, app/views/dolls/edit.html.erb, app/views/dolls/show.html.erb, config/routes.rb
- added the edit and update method to the dolls controller
- added the view for edit
@adhamkou please check and merge when good
=> added edit and update for doll

Gemfile, Gemfile.lock, app/controllers/dolls_controller.rb, app/models/doll.rb, app/views/dolls/index.html.erb
=> added search bar to index

app/controllers/bookings_controller.rb, app/models/user.rb, app/views/bookings/my_bookings.html.erb, app/views/bookings/new.html.erb, node_modules/.yarn-integrity
@adhamkou  : the function of set status of bookings already merge inside the page : my_bookings
=> merge the status change funtion on the my_bookings page

app/assets/stylesheets/components/_background.scss, app/assets/stylesheets/components/_cardproduct.scss, app/assets/stylesheets/components/_home.scss, app/assets/stylesheets/components/_index.scss, app/views/dolls/index.html.erb, app/views/dolls/new.html.erb, app/views/dolls/show.html.erb, app/views/shared/_cards.html.erb, db/seeds.rb
- didnt end up changing background colour
- rounded corners on cards 
- made sure all cards in index are same size
- added scroll for description
- changed seed location to real cities
@adhamkou please check and merge
=> Changing background color
